"""Traduzione delle chiavi semantiche del Conto Economico in voci originali."""

CAMPI_CONTO_ECONOMICO = {
    'a_tot_val_della_produzione': 'A. TOT. VAL. DELLA PRODUZIONE',
    'a1_ricavi_vendite_e_prestazioni': 'A.1. Ricavi vendite e prestazioni',
    'a2_var_rimanenze_prodotti': 'A.2. Var. rimanenze prodotti',
    'a3_variazione_lavori': 'A.3. Variazione lavori',
    'a2_plus_a3_totale_variazioni': 'A.2. + A.3. Totale Variazioni',
    'a4_incrementi_di_immob': 'A.4. Incrementi di immob.',
    'a5_altri_ricavi': 'A.5. Altri ricavi',
    'contributi_in_conto_esercizio': 'Contributi in conto esercizio',
    'b_costi_della_produzione': 'B. COSTI DELLA PRODUZIONE',
    'b6_materie_prime_e_consumo': 'B.6. Materie prime e consumo',
    'b7_servizi': 'B.7. Servizi',
    'b8_godimento_beni_di_terzi': 'B.8. Godimento beni di terzi',
    'b9_totale_costi_del_personale': 'B.9. Totale costi del personale',
    'b9a_salari_e_stipendi': 'B.9.a. Salari e stipendi',
    'b9b_oneri_sociali': 'B.9.b. Oneri sociali',
    'b9c_tratt_fine_rapporto': 'B.9.c. Tratt. fine rapporto',
    'b9d_tratt_di_quiescenza': 'B.9.d. Tratt. di quiescenza',
    'b9e_altri_costi': 'B.9.e. Altri costi',
    'b9f_tfr_plus_quiescenza_plus_altri_costi': 'B.9.f. TFR + quiescenza + altri costi',
    'b10_tot_ammortamenti_e_svalut': 'B.10. TOT Ammortamenti e svalut.',
    'b10a_amm_immob_immat': 'B.10.a. Amm. Immob. Immat.',
    'b10b_amm_immob_mat': 'B.10.b. Amm. Immob. Mat.',
    'b10c_altre_svalut_immob': 'B.10.c. Altre svalut. Immob.',
    'b10aplusbplusc_amm_e_svalut_delle_immob': 'B.10.a+b+c. Amm. e svalut. delle immob.',
    'b10d_svalut_crediti': 'B.10.d. Svalut. crediti',
    'b11_variazione_materie': 'B.11. Variazione materie',
    'b12_accantonamenti_per_rischi': 'B.12. Accantonamenti per rischi',
    'b13_altri_accantonamenti': 'B.13. Altri accantonamenti',
    'b14_oneri_diversi_di_gestione': 'B.14. Oneri diversi di gestione',
    'risultato_operativo': 'RISULTATO OPERATIVO',
    'valore_aggiunto': 'Valore Aggiunto',
    'c_totale_proventi_e_oneri_finanziari': 'C. TOTALE PROVENTI E ONERI FINANZIARI',
    'c15_tot_proventi_da_partecip': 'C.15. Tot. proventi da partecip.',
    'c15_tot_proventi_da_partecip__di_cui_verso_contranti_collegate_contrte_e_sottoposte_ctrl_controllanti': 'di cui: verso contr.anti, collegate, contr.te e sottoposte ctrl controllanti',
    'c15_tot_proventi_da_partecip__di_cui_verso_contranti_collegate_contrte_e_sottoposte_ctrl_controllanti__di_cui_da_imprese_controllanti': 'di cui: da imprese controllanti',
    'c15_tot_proventi_da_partecip__di_cui_verso_contranti_collegate_contrte_e_sottoposte_ctrl_controllanti__di_cui_da_imprese_controllanti__di_cui_da_imprese_sottoposte_al_controllo_delle_controllanti': 'di cui: da imprese sottoposte al controllo delle controllanti',
    'c16_tot_altri_proventi': 'C.16. TOT Altri Proventi',
    'c16a_da_crediti': 'C.16.a. Da Crediti',
    'c16a_da_crediti__di_cui_verso_contranti_collegate_contrte_e_sottoposte_ctrl_controllanti': 'di cui: verso contr.anti, collegate, contr.te e sottoposte ctrl controllanti',
    'c16a_da_crediti__di_cui_verso_contranti_collegate_contrte_e_sottoposte_ctrl_controllanti__di_cui_da_imprese_sottoposte_al_controllo_delle_controllanti': 'di cui: da imprese sottoposte al controllo delle controllanti',
    'c16b_da_titoli_iscr_imm': 'C.16.b. Da titoli iscr. imm.',
    'c16c_da_titoli_iscr_attcircol': 'C.16.c. Da titoli iscr. att.circol.',
    'c16bplusc_proventi_da_titoli': 'C.16.b+c. Proventi da Titoli',
    'c16d_proventi_fin_diversi': 'C.16.d. Proventi fin. Diversi',
    'c16d_proventi_fin_diversi__di_cui_verso_contranti_collegate_contrte_e_sottoposte_ctrl_controllantil': 'di cui: verso contr.anti, collegate, contr.te e sottoposte ctrl controllantil',
    'c16d_proventi_fin_diversi__di_cui_verso_contranti_collegate_contrte_e_sottoposte_ctrl_controllantil__di_cui_da_imprese_sottoposte_al_controllo_delle_controllanti': 'di cui: da imprese sottoposte al controllo delle controllanti',
    'c17_totale_oneri_finanziari': 'C.17. Totale Oneri finanziari',
    'c17_totale_oneri_finanziari__di_cui_verso_contranti_collegate_contrte_e_sottoposte_ctrl_controllanti': 'di cui: verso contr.anti, collegate, contr.te e sottoposte ctrl controllanti',
    'c17_totale_oneri_finanziari__di_cui_verso_contranti_collegate_contrte_e_sottoposte_ctrl_controllanti__di_cui_da_imprese_sottoposte_al_controllo_delle_controllanti': 'di cui: da imprese sottoposte al controllo delle controllanti',
    'c17bis_utili_e_perdite_su_cambi': 'C.17.bis Utili e perdite su cambi',
    'd_totale_rettifiche_att_finanz': 'D. TOTALE RETTIFICHE ATT. FINANZ.',
    'd18_tot_rivalutazioni': 'D.18. TOT Rivalutazioni',
    'd18a_rivalut_di_partec': 'D.18.a. Rivalut. di partec.',
    'd18b_rivalut_di_altre_imm_fin': 'D.18.b. Rivalut. di altre imm. fin.',
    'd18c_rivalut_di_titoli': 'D.18.c. Rivalut. di titoli',
    'd18d_rivalut_di_strumenti_finanziari_derivati': 'D.18.d. Rivalut. di strumenti finanziari derivati',
    'rivalut_di_attivita_finanziarie_per_la_gestione_accentrata_della_tesoreria': 'Rivalut. di attività finanziarie per la gestione accentrata della tesoreria',
    'd19_tot_svalutazioni': 'D.19. TOT Svalutazioni',
    'd19a_svalut_di_partec': 'D.19.a. Svalut. di partec.',
    'd19b_svalut_di_altre_imm_fin': 'D.19.b. Svalut. di altre imm. fin.',
    'd19c_svalut_di_titoli': 'D.19.c. Svalut. di titoli',
    'd19d_svalut_di_strumenti_finanziari_derivati': 'D.19.d. Svalut. di strumenti finanziari derivati',
    'svalut_di_attivita_finanziarie_per_la_gestione_accentrata_della_tesoreria': 'Svalut. di attività finanziarie per la gestione accentrata della tesoreria',
    'totale_proventi_frac_oneri_straordinari': 'TOTALE PROVENTI/ONERI STRAORDINARI',
    'proventi_straordinari': 'Proventi Straordinari',
    'di_cui_plusvalenze': 'di cui plusvalenze',
    'oneri_straordinari': 'Oneri Straordinari',
    'di_cui_minusvalenze': 'di cui minusvalenze',
    'di_cui_imposte_esercizio_precedente': 'di cui imposte esercizio precedente',
    'risultato_prima_delle_imposte': 'RISULTATO PRIMA DELLE IMPOSTE',
    '20_totale_imposte_sul_reddito_correnti_differite_e_anticipate': '20. Totale Imposte sul reddito correnti, differite e anticipate',
    'imposte_correnti': 'Imposte correnti',
    'imposte_relative_a_esercizi_precedenti': 'Imposte relative a esercizi precedenti',
    'imposte_differite_e_anticipate': 'Imposte differite e anticipate',
    'imposte_differite__plus_frac___': 'Imposte differite (+/-)',
    'imposte_anticipate__plus_frac___': 'Imposte anticipate (+/-)',
    'prov__oneri__da_adesione_al_regime_di_trasparenza_fiscale': 'Prov. (oneri) da adesione al regime di trasparenza fiscale',
    '21_utile_frac_perdita_di_esercizio': '21. UTILE/PERDITA DI ESERCIZIO',
    'utile_frac_perdita_di_esercizio_di_pert_di_terzi': 'UTILE/PERDITA DI ESERCIZIO di pert. di TERZI',
    'utile_frac_perdita_di_esercizio_di_pert_del_gruppo': 'UTILE/PERDITA DI ESERCIZIO di pert. del GRUPPO',
    'dipendenti': 'Dipendenti',
}
